format_version: 3
pipelines:
  openSUSE.QA.Maint:
    group: openSUSE.Checkers
    lock_behavior: unlockWhenFinished
    environment_variables:
      OSC_CONFIG: /home/go/config/oscrc-xcdchk
    materials:
      script:
        git: https://github.com/openSUSE/openSUSE-release-tools.git
    stages:
    - Run:
        approval: manual
        resources:
          - repo-checker
        tasks:
          - script: |-
             ./xcdchk.py
